### ISSUE TITLE
Media Queries not working.

### ISSUE THREAD

**Issue by tzsk** [voku/CssToInlineStyles#25]
Everything is working perfectly but when I try to insert media query in my CSS file it ignores that.

My CSS:

```css
*{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box}

body, html {margin: 0;padding: 0;width: 100%;}
div.row {width: 100%;display: block;clear: both;}
div.col-25 { width: 25%;float: left; display: block;padding: 10px;}
div.content {width:100%; background: #eee;padding: 10px;}

@media only screen and (min-width: 360px) {
	div.col-25 { width: 100%; float: left; display: block;padding: 10px;}
}
```

My HTML:

```html
<!DOCTYPE html>
<html>
<head>
	<title>Testing</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>

<div class="row">
	<div class="col-25">
		<div class="content">Hello World!</div>
	</div>
	<div class="col-25">
		<div class="content">Hello World!</div>
	</div>
	<div class="col-25">
		<div class="content">Hello World!</div>
	</div>
	<div class="col-25">
		<div class="content">Hello World!</div>
	</div>
</div>

</body>
</html>
```

My PHP:

```php
$cssToInlineStyles= new voku\CssToInlineStyles\CssToInlineStyles();
$cssToInlineStyles->setExcludeMediaQueries(false); // I even set the exclude media to false.
$cssToInlineStyles->setHTML($html);
$cssToInlineStyles->setCSS($css);
$html = $cssToInlineStyles->convert();
```
